title = "GLB 2021"
baseURL = "https://graph-learning-benchmarks.github.io"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-183489314-1"

[params]
  env = "production"
  favicon = ""
  site_logo = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/glb-bg.jpg"
  recent_posts_number = 0

[menu]

  [[menu.main]]
      name = "Overview"
      weight = 1
      identifier = "overview"
      url = "/#overview"

  [[menu.main]]
      name = "Call for Papers"
      weight = 2
      identifier = "call-for-papers"
      url = "/#call-for-papers"

  [[menu.main]]
      name = "Organizers"
      weight = 3
      identifier = "organizers"
      url = "/#organizers"